class PiperVoiceAsset {
  const PiperVoiceAsset({
    required this.prefix,
    required this.downloadSizeBytes,
  });

  final String prefix;
  final int downloadSizeBytes;
}

/// Full-precision Piper voice packages published in the official Sherpa-ONNX
/// `tts-models` release. FP16 and INT8 variants are intentionally omitted
/// because they duplicate the same voice and quality choices.
const List<PiperVoiceAsset> piperVoiceAssets = [
  PiperVoiceAsset(prefix: 'ar_JO-SA_dii-high', downloadSizeBytes: 66982233),
  PiperVoiceAsset(prefix: 'ar_JO-SA_miro-high', downloadSizeBytes: 66907333),
  PiperVoiceAsset(prefix: 'ar_JO-SA_miro_V2-high', downloadSizeBytes: 66977293),
  PiperVoiceAsset(prefix: 'ar_JO-kareem-low', downloadSizeBytes: 67117397),
  PiperVoiceAsset(prefix: 'ar_JO-kareem-medium', downloadSizeBytes: 67177830),
  PiperVoiceAsset(prefix: 'ca_ES-upc_ona-medium', downloadSizeBytes: 67223188),
  PiperVoiceAsset(prefix: 'ca_ES-upc_ona-x_low', downloadSizeBytes: 26522253),
  PiperVoiceAsset(prefix: 'ca_ES-upc_pau-x_low', downloadSizeBytes: 26520095),
  PiperVoiceAsset(prefix: 'cs_CZ-jirka-low', downloadSizeBytes: 67185771),
  PiperVoiceAsset(prefix: 'cs_CZ-jirka-medium', downloadSizeBytes: 67212775),
  PiperVoiceAsset(prefix: 'cy_GB-bu_tts-medium', downloadSizeBytes: 80313215),
  PiperVoiceAsset(
    prefix: 'cy_GB-gwryw_gogleddol-medium',
    downloadSizeBytes: 67230234,
  ),
  PiperVoiceAsset(
    prefix: 'da_DK-talesyntese-medium',
    downloadSizeBytes: 67185257,
  ),
  PiperVoiceAsset(prefix: 'de_DE-dii-high', downloadSizeBytes: 67200058),
  PiperVoiceAsset(prefix: 'de_DE-eva_k-x_low', downloadSizeBytes: 26521242),
  PiperVoiceAsset(prefix: 'de_DE-glados-high', downloadSizeBytes: 115594308),
  PiperVoiceAsset(prefix: 'de_DE-glados-low', downloadSizeBytes: 67222575),
  PiperVoiceAsset(prefix: 'de_DE-glados-medium', downloadSizeBytes: 67214838),
  PiperVoiceAsset(
    prefix: 'de_DE-glados_turret-high',
    downloadSizeBytes: 115573536,
  ),
  PiperVoiceAsset(
    prefix: 'de_DE-glados_turret-low',
    downloadSizeBytes: 67206901,
  ),
  PiperVoiceAsset(
    prefix: 'de_DE-glados_turret-medium',
    downloadSizeBytes: 67197213,
  ),
  PiperVoiceAsset(prefix: 'de_DE-karlsson-low', downloadSizeBytes: 67100500),
  PiperVoiceAsset(prefix: 'de_DE-kerstin-low', downloadSizeBytes: 67107768),
  PiperVoiceAsset(prefix: 'de_DE-miro-high', downloadSizeBytes: 67160790),
  PiperVoiceAsset(prefix: 'de_DE-pavoque-low', downloadSizeBytes: 67113377),
  PiperVoiceAsset(prefix: 'de_DE-ramona-low', downloadSizeBytes: 67084795),
  PiperVoiceAsset(prefix: 'de_DE-thorsten-high', downloadSizeBytes: 115591546),
  PiperVoiceAsset(prefix: 'de_DE-thorsten-low', downloadSizeBytes: 67101576),
  PiperVoiceAsset(prefix: 'de_DE-thorsten-medium', downloadSizeBytes: 67214254),
  PiperVoiceAsset(
    prefix: 'de_DE-thorsten_emotional-medium',
    downloadSizeBytes: 80215792,
  ),
  PiperVoiceAsset(prefix: 'el_GR-rapunzelina-low', downloadSizeBytes: 67105521),
  PiperVoiceAsset(prefix: 'en_GB-alan-low', downloadSizeBytes: 67086942),
  PiperVoiceAsset(prefix: 'en_GB-alan-medium', downloadSizeBytes: 67220121),
  PiperVoiceAsset(prefix: 'en_GB-alba-medium', downloadSizeBytes: 67212349),
  PiperVoiceAsset(prefix: 'en_GB-aru-medium', downloadSizeBytes: 80309222),
  PiperVoiceAsset(prefix: 'en_GB-cori-high', downloadSizeBytes: 115574061),
  PiperVoiceAsset(prefix: 'en_GB-cori-medium', downloadSizeBytes: 67257412),
  PiperVoiceAsset(prefix: 'en_GB-dii-high', downloadSizeBytes: 67229442),
  PiperVoiceAsset(
    prefix: 'en_GB-jenny_dioco-medium',
    downloadSizeBytes: 67225842,
  ),
  PiperVoiceAsset(prefix: 'en_GB-miro-high', downloadSizeBytes: 67194499),
  PiperVoiceAsset(
    prefix: 'en_GB-northern_english_male-medium',
    downloadSizeBytes: 67210490,
  ),
  PiperVoiceAsset(prefix: 'en_GB-semaine-medium', downloadSizeBytes: 80241918),
  PiperVoiceAsset(
    prefix: 'en_GB-southern_english_female-low',
    downloadSizeBytes: 67073626,
  ),
  PiperVoiceAsset(
    prefix: 'en_GB-southern_english_female-medium',
    downloadSizeBytes: 80275090,
  ),
  PiperVoiceAsset(
    prefix: 'en_GB-southern_english_female_medium',
    downloadSizeBytes: 80253832,
  ),
  PiperVoiceAsset(
    prefix: 'en_GB-southern_english_male-medium',
    downloadSizeBytes: 80299212,
  ),
  PiperVoiceAsset(prefix: 'en_GB-sweetbbak-amy', downloadSizeBytes: 115595629),
  PiperVoiceAsset(prefix: 'en_GB-vctk-medium', downloadSizeBytes: 80488085),
  PiperVoiceAsset(prefix: 'en_US-amy-low', downloadSizeBytes: 67095344),
  PiperVoiceAsset(prefix: 'en_US-amy-medium', downloadSizeBytes: 67223746),
  PiperVoiceAsset(prefix: 'en_US-arctic-medium', downloadSizeBytes: 80255511),
  PiperVoiceAsset(prefix: 'en_US-bryce-medium', downloadSizeBytes: 67278133),
  PiperVoiceAsset(prefix: 'en_US-danny-low', downloadSizeBytes: 67107780),
  PiperVoiceAsset(prefix: 'en_US-glados-high', downloadSizeBytes: 115586982),
  PiperVoiceAsset(prefix: 'en_US-glados', downloadSizeBytes: 67208137),
  PiperVoiceAsset(
    prefix: 'en_US-hfc_female-medium',
    downloadSizeBytes: 67228166,
  ),
  PiperVoiceAsset(prefix: 'en_US-hfc_male-medium', downloadSizeBytes: 67214049),
  PiperVoiceAsset(prefix: 'en_US-joe-medium', downloadSizeBytes: 67169394),
  PiperVoiceAsset(prefix: 'en_US-john-medium', downloadSizeBytes: 67249181),
  PiperVoiceAsset(prefix: 'en_US-kathleen-low', downloadSizeBytes: 67118360),
  PiperVoiceAsset(prefix: 'en_US-kristin-medium', downloadSizeBytes: 67259230),
  PiperVoiceAsset(prefix: 'en_US-kusal-medium', downloadSizeBytes: 67219292),
  PiperVoiceAsset(prefix: 'en_US-l2arctic-medium', downloadSizeBytes: 80314104),
  PiperVoiceAsset(prefix: 'en_US-lessac-high', downloadSizeBytes: 115545841),
  PiperVoiceAsset(prefix: 'en_US-lessac-low', downloadSizeBytes: 67097098),
  PiperVoiceAsset(prefix: 'en_US-lessac-medium', downloadSizeBytes: 67230653),
  PiperVoiceAsset(prefix: 'en_US-libritts-high', downloadSizeBytes: 131033598),
  PiperVoiceAsset(
    prefix: 'en_US-libritts_r-medium',
    downloadSizeBytes: 82038311,
  ),
  PiperVoiceAsset(prefix: 'en_US-ljspeech-high', downloadSizeBytes: 115817679),
  PiperVoiceAsset(prefix: 'en_US-ljspeech-medium', downloadSizeBytes: 67169893),
  PiperVoiceAsset(prefix: 'en_US-miro-high', downloadSizeBytes: 67198472),
  PiperVoiceAsset(prefix: 'en_US-norman-medium', downloadSizeBytes: 67203672),
  PiperVoiceAsset(
    prefix: 'en_US-reza_ibrahim-medium',
    downloadSizeBytes: 67214755,
  ),
  PiperVoiceAsset(prefix: 'en_US-ryan-high', downloadSizeBytes: 115630708),
  PiperVoiceAsset(prefix: 'en_US-ryan-low', downloadSizeBytes: 67100179),
  PiperVoiceAsset(prefix: 'en_US-ryan-medium', downloadSizeBytes: 67213100),
  PiperVoiceAsset(prefix: 'en_US-sam-medium', downloadSizeBytes: 67249919),
  PiperVoiceAsset(prefix: 'es-glados-medium', downloadSizeBytes: 67204723),
  PiperVoiceAsset(prefix: 'es_AR-daniela-high', downloadSizeBytes: 115562134),
  PiperVoiceAsset(prefix: 'es_ES-carlfm-x_low', downloadSizeBytes: 26520563),
  PiperVoiceAsset(prefix: 'es_ES-davefx-medium', downloadSizeBytes: 67184952),
  PiperVoiceAsset(prefix: 'es_ES-glados-medium', downloadSizeBytes: 67214285),
  PiperVoiceAsset(prefix: 'es_ES-miro-high', downloadSizeBytes: 67162898),
  PiperVoiceAsset(prefix: 'es_ES-sharvard-medium', downloadSizeBytes: 80318184),
  PiperVoiceAsset(prefix: 'es_MX-ald-medium', downloadSizeBytes: 67196497),
  PiperVoiceAsset(prefix: 'es_MX-claude-high', downloadSizeBytes: 67207890),
  PiperVoiceAsset(prefix: 'eu_ES-antton-medium', downloadSizeBytes: 67216651),
  PiperVoiceAsset(prefix: 'eu_ES-maider-medium', downloadSizeBytes: 67247291),
  PiperVoiceAsset(prefix: 'fa-haaniye_low', downloadSizeBytes: 67092634),
  PiperVoiceAsset(prefix: 'fa_IR-amir-medium', downloadSizeBytes: 67180373),
  PiperVoiceAsset(prefix: 'fa_IR-ganji-medium', downloadSizeBytes: 67186157),
  PiperVoiceAsset(
    prefix: 'fa_IR-ganji_adabi-medium',
    downloadSizeBytes: 67221431,
  ),
  PiperVoiceAsset(prefix: 'fa_IR-gyro-medium', downloadSizeBytes: 67183308),
  PiperVoiceAsset(
    prefix: 'fa_IR-reza_ibrahim-medium',
    downloadSizeBytes: 67187249,
  ),
  PiperVoiceAsset(
    prefix: 'fa_en-rezahedayatfar-ibrahimwalk-medium',
    downloadSizeBytes: 67246929,
  ),
  PiperVoiceAsset(prefix: 'fi_FI-harri-low', downloadSizeBytes: 67101909),
  PiperVoiceAsset(prefix: 'fi_FI-harri-medium', downloadSizeBytes: 67205198),
  PiperVoiceAsset(prefix: 'fr_FR-gilles-low', downloadSizeBytes: 67094350),
  PiperVoiceAsset(prefix: 'fr_FR-miro-high', downloadSizeBytes: 67162880),
  PiperVoiceAsset(prefix: 'fr_FR-siwis-low', downloadSizeBytes: 26522254),
  PiperVoiceAsset(prefix: 'fr_FR-siwis-medium', downloadSizeBytes: 67207459),
  PiperVoiceAsset(prefix: 'fr_FR-tjiho-model1', downloadSizeBytes: 67204019),
  PiperVoiceAsset(prefix: 'fr_FR-tjiho-model2', downloadSizeBytes: 67204483),
  PiperVoiceAsset(prefix: 'fr_FR-tjiho-model3', downloadSizeBytes: 67251174),
  PiperVoiceAsset(prefix: 'fr_FR-tom-medium', downloadSizeBytes: 67202955),
  PiperVoiceAsset(prefix: 'fr_FR-upmc-medium', downloadSizeBytes: 80422639),
  PiperVoiceAsset(prefix: 'hi_IN-pratham-medium', downloadSizeBytes: 67238438),
  PiperVoiceAsset(
    prefix: 'hi_IN-priyamvada-medium',
    downloadSizeBytes: 67240610,
  ),
  PiperVoiceAsset(prefix: 'hi_IN-rohan-medium', downloadSizeBytes: 67221139),
  PiperVoiceAsset(prefix: 'hu_HU-anna-medium', downloadSizeBytes: 67167701),
  PiperVoiceAsset(prefix: 'hu_HU-berta-medium', downloadSizeBytes: 67178197),
  PiperVoiceAsset(prefix: 'hu_HU-imre-medium', downloadSizeBytes: 67218203),
  PiperVoiceAsset(prefix: 'id_ID-news_tts-medium', downloadSizeBytes: 67243848),
  PiperVoiceAsset(prefix: 'is_IS-bui-medium', downloadSizeBytes: 67271654),
  PiperVoiceAsset(prefix: 'is_IS-salka-medium', downloadSizeBytes: 67359734),
  PiperVoiceAsset(prefix: 'is_IS-steinn-medium', downloadSizeBytes: 67377681),
  PiperVoiceAsset(prefix: 'is_IS-ugla-medium', downloadSizeBytes: 67376655),
  PiperVoiceAsset(prefix: 'it_IT-dii-high', downloadSizeBytes: 67196676),
  PiperVoiceAsset(prefix: 'it_IT-miro-high', downloadSizeBytes: 67162890),
  PiperVoiceAsset(prefix: 'it_IT-paola-medium', downloadSizeBytes: 67221173),
  PiperVoiceAsset(prefix: 'it_IT-riccardo-x_low', downloadSizeBytes: 26496614),
  PiperVoiceAsset(prefix: 'ka_GE-natia-medium', downloadSizeBytes: 67209457),
  PiperVoiceAsset(prefix: 'kk_KZ-iseke-x_low', downloadSizeBytes: 26517675),
  PiperVoiceAsset(prefix: 'kk_KZ-issai-high', downloadSizeBytes: 129278805),
  PiperVoiceAsset(prefix: 'kk_KZ-raya-x_low', downloadSizeBytes: 26497880),
  PiperVoiceAsset(
    prefix: 'ku_TR-berfin_renas-medium',
    downloadSizeBytes: 80263336,
  ),
  PiperVoiceAsset(prefix: 'lb_LU-marylux-medium', downloadSizeBytes: 67184319),
  PiperVoiceAsset(prefix: 'lv_LV-aivars-medium', downloadSizeBytes: 67196173),
  PiperVoiceAsset(prefix: 'ml_IN-arjun-medium', downloadSizeBytes: 67222458),
  PiperVoiceAsset(prefix: 'ml_IN-meera-medium', downloadSizeBytes: 67195010),
  PiperVoiceAsset(prefix: 'ne_NP-chitwan-medium', downloadSizeBytes: 67213467),
  PiperVoiceAsset(prefix: 'ne_NP-google-medium', downloadSizeBytes: 80242801),
  PiperVoiceAsset(prefix: 'ne_NP-google-x_low', downloadSizeBytes: 33214875),
  PiperVoiceAsset(prefix: 'nl_BE-nathalie-medium', downloadSizeBytes: 67226472),
  PiperVoiceAsset(prefix: 'nl_BE-nathalie-x_low', downloadSizeBytes: 26502603),
  PiperVoiceAsset(prefix: 'nl_BE-rdh-medium', downloadSizeBytes: 67047636),
  PiperVoiceAsset(prefix: 'nl_BE-rdh-x_low', downloadSizeBytes: 26454425),
  PiperVoiceAsset(prefix: 'nl_NL-alex-medium', downloadSizeBytes: 67172584),
  PiperVoiceAsset(prefix: 'nl_NL-dii-high', downloadSizeBytes: 67203791),
  PiperVoiceAsset(prefix: 'nl_NL-miro-high', downloadSizeBytes: 67169101),
  PiperVoiceAsset(prefix: 'nl_NL-pim-medium', downloadSizeBytes: 67240538),
  PiperVoiceAsset(prefix: 'nl_NL-ronnie-medium', downloadSizeBytes: 67194164),
  PiperVoiceAsset(
    prefix: 'no_NO-talesyntese-medium',
    downloadSizeBytes: 67194829,
  ),
  PiperVoiceAsset(prefix: 'pl_PL-bass-high', downloadSizeBytes: 115576949),
  PiperVoiceAsset(prefix: 'pl_PL-darkman-medium', downloadSizeBytes: 67215635),
  PiperVoiceAsset(prefix: 'pl_PL-gosia-medium', downloadSizeBytes: 67211182),
  PiperVoiceAsset(
    prefix: 'pl_PL-jarvis_wg_glos-medium',
    downloadSizeBytes: 67244103,
  ),
  PiperVoiceAsset(
    prefix: 'pl_PL-justyna_wg_glos-medium',
    downloadSizeBytes: 67242145,
  ),
  PiperVoiceAsset(
    prefix: 'pl_PL-mc_speech-medium',
    downloadSizeBytes: 67234285,
  ),
  PiperVoiceAsset(
    prefix: 'pl_PL-meski_wg_glos-medium',
    downloadSizeBytes: 67246175,
  ),
  PiperVoiceAsset(
    prefix: 'pl_PL-zenski_wg_glos-medium',
    downloadSizeBytes: 67251520,
  ),
  PiperVoiceAsset(prefix: 'pt_BR-cadu-medium', downloadSizeBytes: 67207562),
  PiperVoiceAsset(prefix: 'pt_BR-dii-high', downloadSizeBytes: 67238016),
  PiperVoiceAsset(prefix: 'pt_BR-edresson-low', downloadSizeBytes: 67081775),
  PiperVoiceAsset(prefix: 'pt_BR-faber-medium', downloadSizeBytes: 67183065),
  PiperVoiceAsset(prefix: 'pt_BR-jeff-medium', downloadSizeBytes: 67207052),
  PiperVoiceAsset(prefix: 'pt_BR-miro-high', downloadSizeBytes: 67207707),
  PiperVoiceAsset(prefix: 'pt_PT-dii-high', downloadSizeBytes: 67243408),
  PiperVoiceAsset(prefix: 'pt_PT-miro-high', downloadSizeBytes: 67208098),
  PiperVoiceAsset(prefix: 'pt_PT-tugao-medium', downloadSizeBytes: 67195014),
  PiperVoiceAsset(prefix: 'ro_RO-mihai-medium', downloadSizeBytes: 67182137),
  PiperVoiceAsset(prefix: 'ru_RU-denis-medium', downloadSizeBytes: 67190991),
  PiperVoiceAsset(prefix: 'ru_RU-dmitri-medium', downloadSizeBytes: 67188551),
  PiperVoiceAsset(prefix: 'ru_RU-irina-medium', downloadSizeBytes: 67153308),
  PiperVoiceAsset(prefix: 'ru_RU-ruslan-medium', downloadSizeBytes: 67210684),
  PiperVoiceAsset(prefix: 'sk_SK-lili-medium', downloadSizeBytes: 67183092),
  PiperVoiceAsset(prefix: 'sl_SI-artur-medium', downloadSizeBytes: 67025668),
  PiperVoiceAsset(prefix: 'sq_AL-edon-medium', downloadSizeBytes: 67191820),
  PiperVoiceAsset(
    prefix: 'sr_RS-serbski_institut-medium',
    downloadSizeBytes: 80298557,
  ),
  PiperVoiceAsset(prefix: 'sv_SE-alma-medium', downloadSizeBytes: 67154700),
  PiperVoiceAsset(prefix: 'sv_SE-lisa-medium', downloadSizeBytes: 67223955),
  PiperVoiceAsset(prefix: 'sv_SE-nst-medium', downloadSizeBytes: 67144884),
  PiperVoiceAsset(prefix: 'sw_CD-lanfrica-medium', downloadSizeBytes: 67217230),
  PiperVoiceAsset(prefix: 'tr_TR-dfki-medium', downloadSizeBytes: 67201221),
  PiperVoiceAsset(
    prefix: 'tr_TR-fahrettin-medium',
    downloadSizeBytes: 67212827,
  ),
  PiperVoiceAsset(prefix: 'tr_TR-fettah-medium', downloadSizeBytes: 67174342),
  PiperVoiceAsset(prefix: 'uk_UA-lada-x_low', downloadSizeBytes: 26520908),
  PiperVoiceAsset(
    prefix: 'uk_UA-ukrainian_tts-medium',
    downloadSizeBytes: 80355083,
  ),
  PiperVoiceAsset(prefix: 'ur_PK-fasih-medium', downloadSizeBytes: 67227718),
  PiperVoiceAsset(
    prefix: 'vi_VN-25hours_single-low',
    downloadSizeBytes: 67059380,
  ),
  PiperVoiceAsset(prefix: 'vi_VN-vais1000-medium', downloadSizeBytes: 67154040),
  PiperVoiceAsset(prefix: 'vi_VN-vivos-x_low', downloadSizeBytes: 33409065),
  PiperVoiceAsset(prefix: 'zh_CN-chaowen-medium', downloadSizeBytes: 60443846),
  PiperVoiceAsset(prefix: 'zh_CN-huayan-medium', downloadSizeBytes: 67255926),
  PiperVoiceAsset(prefix: 'zh_CN-xiao_ya-medium', downloadSizeBytes: 60462944),
];
